using System.Numerics;
using Raylib_cs;
using MouseHouse.Scenes.Activities.Retro;

namespace MouseHouse.Scenes.Activities;

/// <summary>
/// TetraVex — square tiles each carry four numbers (one per edge). Drop the
/// nine tiles into a 3×3 grid so every shared edge matches. Tiles for the
/// puzzle are generated by laying down a valid solution and then scrambling
/// the bag.
/// </summary>
public class TetraVexActivity : IActivity
{
    private const int FrameInset = 3;
    private const int Size = 3;            // 3x3 grid
    private const int Tile = 60;
    private const int Margin = 18;
    private const int TrayPad = 12;

    public Vector2 PanelSize => new(
        2 * FrameInset + 2 * Margin + Size * Tile + TrayPad + 3 * (Tile + 4),
        2 * FrameInset + RetroWidgets.TitleBarHeight + RetroWidgets.MenuBarHeight
            + Margin + Size * Tile + Margin + RetroWidgets.StatusBarHeight);

    public bool IsFinished { get; private set; }

    private readonly RetroHelp _help = new()
    {
        Title = "TetraVex — How to play",
        Lines = new[]
        {
            "Each tile carries four numbers, one per edge.",
            "Drop tiles into the 3x3 board so every shared",
            "edge between adjacent tiles shows the same number.",
            "Click a tile to pick it up, click a board slot",
            "to place it (or swap with the tile already there).",
        },
        DiagramHeight = 80,
        Diagram = r =>
        {
            // Two tiles side by side; the right tile's W matches the left tile's E.
            const int sz = 70;
            int x0 = (int)(r.X + (r.Width - 2 * sz - 8) / 2);
            int y = (int)r.Y;
            DrawSampleTile(new Rectangle(x0, y, sz, sz), 5, 7, 2, 4);
            DrawSampleTile(new Rectangle(x0 + sz + 8, y, sz, sz), 1, 9, 6, 7);
            // Highlight the matching shared edge in green.
            int sharedX = x0 + sz + 4;
            for (int yy = y + sz / 2 - 8; yy <= y + sz / 2 + 8; yy++)
                Raylib.DrawRectangle(sharedX, yy, 4, 1, new Color(64, 200, 64, 255));
        },
    };

    private static void DrawSampleTile(Rectangle rect, int n, int e, int s, int w)
    {
        RetroSkin.DrawRaised(rect);
        int x = (int)rect.X, y = (int)rect.Y, sz = (int)rect.Width;
        Raylib.DrawLine(x, y, x + sz, y + sz, RetroSkin.Shadow);
        Raylib.DrawLine(x + sz, y, x, y + sz, RetroSkin.Shadow);
        var col = RetroSkin.BodyText;
        DrawNum(n, x + sz / 2, y + 2, col);
        DrawNum(s, x + sz / 2, y + sz - 18, col);
        DrawNum(w, x + 4, y + sz / 2 - 8, col);
        DrawNum(e, x + sz - 14, y + sz / 2 - 8, col);
    }

    private record class TileData(int N, int E, int S, int W) { public int Slot = -1; public int Tray; }
    private List<TileData> _tiles = new();
    private int _picked = -1;
    private bool _won;
    private readonly Random _rng = new();

    public void Load() => Reset();

    private void Reset()
    {
        // Build a valid 3x3 solution: each cell has random N/E/S/W in 0..9 such
        // that adjacent edges match.
        int[,] N = new int[Size, Size];
        int[,] E = new int[Size, Size];
        int[,] S = new int[Size, Size];
        int[,] W = new int[Size, Size];
        for (int y = 0; y < Size; y++)
            for (int x = 0; x < Size; x++)
            {
                N[x, y] = y == 0 ? _rng.Next(10) : S[x, y - 1];
                W[x, y] = x == 0 ? _rng.Next(10) : E[x - 1, y];
                E[x, y] = _rng.Next(10);
                S[x, y] = _rng.Next(10);
            }

        _tiles.Clear();
        for (int y = 0; y < Size; y++)
            for (int x = 0; x < Size; x++)
                _tiles.Add(new TileData(N[x, y], E[x, y], S[x, y], W[x, y])
                { Slot = -1, Tray = y * Size + x });

        // Shuffle tray order
        for (int i = _tiles.Count - 1; i > 0; i--)
        {
            int j = _rng.Next(i + 1);
            (_tiles[i].Tray, _tiles[j].Tray) = (_tiles[j].Tray, _tiles[i].Tray);
        }
        _picked = -1;
        _won = false;
    }

    private Vector2 SlotPos(int idx)
    {
        int x = idx % Size, y = idx / Size;
        return new Vector2(
            FrameInset + Margin + x * Tile,
            FrameInset + RetroWidgets.TitleBarHeight + RetroWidgets.MenuBarHeight + Margin + y * Tile);
    }

    private Vector2 TrayPos(int trayIdx)
    {
        int x = trayIdx % 3, y = trayIdx / 3;
        return new Vector2(
            FrameInset + Margin + Size * Tile + TrayPad + x * (Tile + 4),
            FrameInset + RetroWidgets.TitleBarHeight + RetroWidgets.MenuBarHeight + Margin + y * (Tile + 4));
    }

    public void Update(float delta, Vector2 mousePos, Vector2 panelOffset,
                       bool leftPressed, bool leftReleased, bool rightPressed)
    {
        var local = mousePos - panelOffset;
        var titleBar = new Rectangle(FrameInset, FrameInset,
            PanelSize.X - 2 * FrameInset, RetroWidgets.TitleBarHeight);
        if (RetroWidgets.DrawTitleBarHitTest(titleBar, local, leftPressed))
        { IsFinished = true; return; }

        var menuBar = new Rectangle(FrameInset, FrameInset + RetroWidgets.TitleBarHeight,
            PanelSize.X - 2 * FrameInset, RetroWidgets.MenuBarHeight);
        switch (RetroWidgets.MenuBarHitTest(menuBar, new[] { "New", "Help" }, local, leftPressed))
        {
            case 0: Reset(); return;
            case 1: _help.Visible = !_help.Visible; return;
        }
        if (_help.HandleInput(local, leftPressed, PanelSize)) return;

        if (!leftPressed) return;

        // Pick up a tile
        for (int i = 0; i < _tiles.Count; i++)
        {
            var t = _tiles[i];
            var pos = t.Slot >= 0 ? SlotPos(t.Slot) : TrayPos(t.Tray);
            if (RetroSkin.PointInRect(local, new Rectangle(pos.X, pos.Y, Tile, Tile)))
            { _picked = i; return; }
        }

        // Drop on slot
        if (_picked >= 0)
        {
            for (int s = 0; s < Size * Size; s++)
            {
                var pos = SlotPos(s);
                if (!RetroSkin.PointInRect(local, new Rectangle(pos.X, pos.Y, Tile, Tile))) continue;
                var picked = _tiles[_picked];
                TileData? occupant = null;
                foreach (var q in _tiles) if (q.Slot == s) { occupant = q; break; }
                int prevSlot = picked.Slot;
                int prevTray = picked.Tray;
                picked.Slot = s;
                if (occupant != null) { occupant.Slot = prevSlot; if (prevSlot < 0) occupant.Tray = prevTray; }
                _picked = -1;
                CheckWin();
                return;
            }
        }
    }

    private void CheckWin()
    {
        var grid = new TileData?[Size, Size];
        foreach (var t in _tiles)
            if (t.Slot >= 0) grid[t.Slot % Size, t.Slot / Size] = t;
        for (int y = 0; y < Size; y++)
            for (int x = 0; x < Size; x++)
            {
                if (grid[x, y] == null) return;
                if (x < Size - 1 && grid[x + 1, y] != null && grid[x, y]!.E != grid[x + 1, y]!.W) return;
                if (y < Size - 1 && grid[x, y + 1] != null && grid[x, y]!.S != grid[x, y + 1]!.N) return;
            }
        _won = true;
    }

    public void Draw(Vector2 panelOffset)
    {
        var panel = new Rectangle(panelOffset.X, panelOffset.Y, PanelSize.X, PanelSize.Y);
        RetroWidgets.DrawWindowFrame(panel);

        var titleBar = new Rectangle(panelOffset.X + FrameInset, panelOffset.Y + FrameInset,
            PanelSize.X - 2 * FrameInset, RetroWidgets.TitleBarHeight);
        RetroWidgets.DrawTitleBarVisual(titleBar, "TetraVex", true);

        var menuBar = new Rectangle(panelOffset.X + FrameInset,
            panelOffset.Y + FrameInset + RetroWidgets.TitleBarHeight,
            PanelSize.X - 2 * FrameInset, RetroWidgets.MenuBarHeight);
        RetroWidgets.MenuBarVisual(menuBar, new[] { "New", "Help" }, -1);

        // Board outline (sunken)
        var board = new Rectangle(
            panelOffset.X + FrameInset + Margin - 3,
            panelOffset.Y + FrameInset + RetroWidgets.TitleBarHeight + RetroWidgets.MenuBarHeight + Margin - 3,
            Size * Tile + 6, Size * Tile + 6);
        RetroSkin.DrawSunken(board, RetroSkin.Face);
        for (int s = 0; s < Size * Size; s++)
        {
            var pos = SlotPos(s);
            Raylib.DrawRectangleLines((int)(panelOffset.X + pos.X), (int)(panelOffset.Y + pos.Y),
                Tile, Tile, RetroSkin.Shadow);
        }

        foreach (var t in _tiles)
        {
            var pos = t.Slot >= 0 ? SlotPos(t.Slot) : TrayPos(t.Tray);
            var abs = new Vector2(panelOffset.X + pos.X, panelOffset.Y + pos.Y);
            DrawTile(abs, t);
            if (_tiles.IndexOf(t) == _picked)
                Raylib.DrawRectangleLinesEx(new Rectangle(abs.X - 2, abs.Y - 2, Tile + 4, Tile + 4),
                    2, new Color(255, 220, 0, 255));
        }

        var status = new Rectangle(panelOffset.X + FrameInset,
            panelOffset.Y + PanelSize.Y - FrameInset - RetroWidgets.StatusBarHeight,
            PanelSize.X - 2 * FrameInset, RetroWidgets.StatusBarHeight);
        RetroWidgets.StatusBar(status,
            _won ? "Solved!" : "Match every shared edge",
            "Pick a tile, drop on a slot");

        _help.Draw(panelOffset, PanelSize);
    }

    private static void DrawTile(Vector2 pos, TileData t)
    {
        var rect = new Rectangle(pos.X, pos.Y, Tile, Tile);
        RetroSkin.DrawRaised(rect);
        // Diagonals to split the tile into 4 triangles
        int x = (int)pos.X, y = (int)pos.Y;
        Raylib.DrawLine(x, y, x + Tile, y + Tile, RetroSkin.Shadow);
        Raylib.DrawLine(x + Tile, y, x, y + Tile, RetroSkin.Shadow);
        // Numbers
        var col = RetroSkin.BodyText;
        DrawNum(t.N, x + Tile / 2, y + 2, col);
        DrawNum(t.S, x + Tile / 2, y + Tile - 18, col);
        DrawNum(t.W, x + 4, y + Tile / 2 - 8, col);
        DrawNum(t.E, x + Tile - 14, y + Tile / 2 - 8, col);
    }

    private static void DrawNum(int n, int x, int y, Color col)
    {
        string s = n.ToString();
        int w = RetroSkin.MeasureText(s, 16);
        RetroSkin.DrawText(s, x - w / 2, y, col, 16);
    }

    public void Close() { }
}
